services:
  postgres_prod:
    container_name: ordemservico_postgres_dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: OrdemServicoDb_Dev
    ports:
      - "5433:5432"
    volumes:
      - pgdata_dev:/var/lib/postgresql/data

  mongodb_prod:
    container_name: ordemservico_mongodb_dev
    ports:
      - "27018:27017"
    volumes:
      - mongodata_dev:/data/db

  rabbitmq_prod:
    container_name: ordemservico_rabbitmq_dev
    ports:
      - "15673:15672"
      - "5673:5672"
    environment:
      RABBITMQ_DEFAULT_USER: dev
      RABBITMQ_DEFAULT_PASS: dev123

volumes:
  pgdata_dev:
  mongodata_dev:
